### ISSUE TITLE
SDK 3.5.0-beta.1 & 2022 Incompatibility

### ISSUE THREAD

**Issue by rhaamo** [BocuD/VRBuildHelper#10]
Hello,

Getting an error when loading the tools on the beta1 for 3.5.0 under unity 2022:

```
Packages\com.bocud.vrbuildhelper\BuildHelper\Editor\AutonomousBuilder.cs(112,22): error CS0104: 'Progress' is an ambiguous reference between 'BocuD.BuildHelper.AutonomousBuilder.AutonomousBuildData.Progress' and 'UnityEditor.Progress'
Packages\com.bocud.vrbuildhelper\BuildHelper\Editor\AutonomousBuilder.cs(113,49): error CS0104: 'Progress' is an ambiguous reference between 'BocuD.BuildHelper.AutonomousBuilder.AutonomousBuildData.Progress' and 'UnityEditor.Progress'
Packages\com.bocud.vrbuildhelper\BuildHelper\Editor\AutonomousBuilder.cs(117,22): error CS0104: 'Progress' is an ambiguous reference between 'BocuD.BuildHelper.AutonomousBuilder.AutonomousBuildData.Progress' and 'UnityEditor.Progress'
Packages\com.bocud.vrbuildhelper\BuildHelper\Editor\AutonomousBuilder.cs(137,41): error CS0104: 'Progress' is an ambiguous reference between 'BocuD.BuildHelper.AutonomousBuilder.AutonomousBuildData.Progress' and 'UnityEditor.Progress'
Packages\com.bocud.vrbuildhelper\BuildHelper\Editor\AutonomousBuilder.cs(163,41): error CS0104: 'Progress' is an ambiguous reference between 'BocuD.BuildHelper.AutonomousBuilder.AutonomousBuildData.Progress' and 'UnityEditor.Progress'
```

I don't really know the code and haven't spent much time understanding it so I just did the crime of renaming `Progress` to `BuildProgress` in some places and it seems to pass build.

Haven't tried yet to build with the tool, but world infos shows at least.

Related issue too: https://github.com/BocuD/VRChatApiTools/issues/10

**Comment by BocuD** [comment]
Yeah, i'm aware of these issues. The change you proposed here does fix it. There are some changes i need to do to properly support SDK 3.3.0 and up, since VRChat rewrote their uploader, and it negates the need for the VRCApiTools uploader. Updating everything to use that takes a while though and i haven't really found the time for this. I hope to fix all these issues sometime soon.
For now you can keep your change; i might publish a hotfix sometime soon implementing something similar but i really don't like supporting the tools as they are right now without moving to the native VRChat uploader, and i suppose this does discourage people from using them for now 😅. For now i'll leave the issue open since it'll remind me to look into this more next week.

**Comment by BocuD** [comment]
This was patched using above change. While this does make buildhelper usable, i won't be doing any release until i have time to properly rework the tool to no longer use my custom uploader, but rather the one that is now provided by VRC.
