### ISSUE TITLE
[BUG] Assets\BocuD\BuildHelper\Editor\BuildHelperBuilder.cs(46,17): error CS0103: The name 'EnvConfig' does not exist in the current context

### ISSUE THREAD

**Issue by Rycia** [BocuD/VRBuildHelper#3]
I encountered an issue with VRBuildHelper, it is a U# error, and hence I am unable to build my VRChat worlds and test them.

I have deleted the assets entirely and re imported it to see if the issue would persist, and it does.
Here is the error.

![image](https://user-images.githubusercontent.com/43384589/180364739-c8c8cdc8-5681-4a21-93c7-4d4581f88a67.png)
![image](https://user-images.githubusercontent.com/43384589/180364800-7bb82fb0-adae-43ce-952b-c3355200ae95.png)

**Comment by BocuD** [comment]
Hey, this is because you are probably using an incompatible BuildHelper / VRCSDK version combination. To solve this you should update to the latest version of the SDK and the latest version of BuildHelper (i believe it is currently still marked as a pre release, i should fix that). Let me know if that solves it.
